<a href="https://colab.research.google.com/github/prof-atritiack/CP2-ML-SERS/blob/main/AULA_06_ML_ENERGIA_SERS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##EXERCÍCIO - MODELO PREDITIVO DE CLASSIFICAÇÃO

Vamos treinar um modelo preditivo de Machine Learning para classificar a estabilidade da rede elétrica.

1 atributo alvo (target) -----> array com referência à coluna 'stabf'
Classes: 'stable' e 'unstable'
Criar uma variável chamada y com os dados da coluna 'stabf'

13 atributos numéricos ------> 12 serão usados como Features para o modelo.
Criar um dataframe com esses 12 atributos e chamar de X.

PREPARAÇÃO DO AMBIENTE

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Algoritmo de regressão logística -----> algoritmo de classificação
from sklearn.linear_model import LogisticRegression
# Separação dos dados de treino e de teste
# No exemplo, usaremos 20% para teste e 80% para treino
# X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
# Métricas de avaliação para classificação
from sklearn.metrics import accuracy_score

Criação do dataframe 'dados'

In [2]:
dados = pd.read_csv('https://raw.githubusercontent.com/prof-atritiack/CP2-ML-SERS/refs/heads/main/Data_for_UCI_named.csv')
dados.head()

       tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [3]:
# Inspeção inicial
dados.shape

(10000, 14)

In [4]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object
dtypes: float64(13), object(1)
memory usage: 1.1+ MB

In [6]:
# Atributos com valores numéricos
dados.describe(include='number')

               tau1          tau2  ...            g4          stab
count  10000.000000  10000.000000  ...  10000.000000  10000.000000
mean       5.250000      5.250001  ...      0.525000      0.015731
std        2.742548      2.742549  ...      0.274255      0.036919
min        0.500793      0.500141  ...      0.050028     -0.080760
25%        2.874892      2.875140  ...      0.287494     -0.015557
50%        5.250004      5.249981  ...      0.525002      0.017142
75%        7.624690      7.624893  ...      0.762433      0.044878
max        9.999469      9.999837  ...      0.999930      0.109403

[8 rows x 13 columns]

In [5]:
# Atributos com valores categóricos
dados.describe(include='object')

           stabf
count      10000
unique         2
top     unstable
freq        6380

In [9]:
# Renomeando os labels
dados['stabf'] = dados['stabf'].replace({'stable': 'REDE ESTÁVEL', 'unstable': 'REDE INSTÁVEL'})
dados.head(10)

       tau1      tau2      tau3  ...        g4      stab          stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  REDE INSTÁVEL
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957   REDE ESTÁVEL
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  REDE INSTÁVEL
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  REDE INSTÁVEL
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  REDE INSTÁVEL
5  6.999209  9.109247  3.784066  ...  0.469931 -0.017385   REDE ESTÁVEL
6  6.710166  3.765204  6.929314  ...  0.376630  0.005954  REDE INSTÁVEL
7  6.953512  1.379125  5.719400  ...  0.380544  0.016634  REDE INSTÁVEL
8  4.689852  4.007747  1.478573  ...  0.482439 -0.038677   REDE ESTÁVEL
9  9.841496  1.413822  9.769856  ...  0.116263  0.012383  REDE INSTÁVEL

[10 rows x 14 columns]

In [10]:
# Quais classes temos na coluna 'stabf' (target)?
dados['stabf'].unique()

array(['REDE INSTÁVEL', 'REDE ESTÁVEL'], dtype=object)

In [11]:
# Quantos registros temos de cada classe?
dados['stabf'].value_counts()

stabf
REDE INSTÁVEL    6380
REDE ESTÁVEL     3620
Name: count, dtype: int64